
server:
  port: 8080
app:
  backend-url: http://localhost:8080

#jwt:
#  secret: ${JWT_SECRET}

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tinderdb
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: smtp.mailtrap.io
    port: 587
    #    username: ${MAIL_USERNAME}
    #    password: ${MAIL_PASSWORD}
    username: your_mailtrap_username
    password: your_mailtrap_password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true



